export type ProvinceData = {
    id: string;
    name: string;
    countryCode: string;
};

export const provincesData: Record<string, ProvinceData[]> = {
    'VN': [
        { id: 'VN-HN', name: 'Hà Nội', countryCode: 'VN' },
        { id: 'VN-SG', name: 'Hồ Chí Minh', countryCode: 'VN' },
        { id: 'VN-DN', name: 'Đà Nẵng', countryCode: 'VN' },
        { id: 'VN-HP', name: 'Hải Phòng', countryCode: 'VN' },
        { id: 'VN-CT', name: 'Cần Thơ', countryCode: 'VN' },
        { id: 'VN-AG', name: 'An Giang', countryCode: 'VN' },
        { id: 'VN-BV', name: 'Bà Rịa - Vũng Tàu', countryCode: 'VN' },
        { id: 'VN-BL', name: 'Bạc Liêu', countryCode: 'VN' },
        { id: 'VN-BG', name: 'Bắc Giang', countryCode: 'VN' },
        { id: 'VN-BK', name: 'Bắc Kạn', countryCode: 'VN' },
        { id: 'VN-BN', name: 'Bắc Ninh', countryCode: 'VN' },
        { id: 'VN-BT', name: 'Bến Tre', countryCode: 'VN' },
        { id: 'VN-BD', name: 'Bình Định', countryCode: 'VN' },
        { id: 'VN-BI', name: 'Bình Dương', countryCode: 'VN' },
        { id: 'VN-BP', name: 'Bình Phước', countryCode: 'VN' },
        { id: 'VN-BU', name: 'Bình Thuận', countryCode: 'VN' },
        { id: 'VN-CM', name: 'Cà Mau', countryCode: 'VN' },
        { id: 'VN-CB', name: 'Cao Bằng', countryCode: 'VN' },
        { id: 'VN-DL', name: 'Đắk Lắk', countryCode: 'VN' },
        { id: 'VN-DT', name: 'Đắk Nông', countryCode: 'VN' },
        { id: 'VN-DB', name: 'Điện Biên', countryCode: 'VN' },
        { id: 'VN-DI', name: 'Đồng Nai', countryCode: 'VN' },
        { id: 'VN-DT', name: 'Đồng Tháp', countryCode: 'VN' },
        { id: 'VN-GL', name: 'Gia Lai', countryCode: 'VN' },
        { id: 'VN-HG', name: 'Hà Giang', countryCode: 'VN' },
        { id: 'VN-HD', name: 'Hà Nam', countryCode: 'VN' },
        { id: 'VN-HT', name: 'Hà Tĩnh', countryCode: 'VN' },
        { id: 'VN-HU', name: 'Hải Dương', countryCode: 'VN' },
        { id: 'VN-HM', name: 'Hậu Giang', countryCode: 'VN' },
        { id: 'VN-HB', name: 'Hòa Bình', countryCode: 'VN' },
        { id: 'VN-HY', name: 'Hưng Yên', countryCode: 'VN' },
        { id: 'VN-KH', name: 'Khánh Hòa', countryCode: 'VN' },
        { id: 'VN-KG', name: 'Kiên Giang', countryCode: 'VN' },
        { id: 'VN-KT', name: 'Kon Tum', countryCode: 'VN' },
        { id: 'VN-LC', name: 'Lai Châu', countryCode: 'VN' },
        { id: 'VN-LD', name: 'Lâm Đồng', countryCode: 'VN' },
        { id: 'VN-LS', name: 'Lạng Sơn', countryCode: 'VN' },
        { id: 'VN-LO', name: 'Lào Cai', countryCode: 'VN' },
        { id: 'VN-LA', name: 'Long An', countryCode: 'VN' },
        { id: 'VN-ND', name: 'Nam Định', countryCode: 'VN' },
        { id: 'VN-NA', name: 'Nghệ An', countryCode: 'VN' },
        { id: 'VN-NB', name: 'Ninh Bình', countryCode: 'VN' },
        { id: 'VN-NT', name: 'Ninh Thuận', countryCode: 'VN' },
        { id: 'VN-PT', name: 'Phú Thọ', countryCode: 'VN' },
        { id: 'VN-PY', name: 'Phú Yên', countryCode: 'VN' },
        { id: 'VN-QB', name: 'Quảng Bình', countryCode: 'VN' },
        { id: 'VN-QM', name: 'Quảng Nam', countryCode: 'VN' },
        { id: 'VN-QG', name: 'Quảng Ngãi', countryCode: 'VN' },
        { id: 'VN-QN', name: 'Quảng Ninh', countryCode: 'VN' },
        { id: 'VN-QT', name: 'Quảng Trị', countryCode: 'VN' },
        { id: 'VN-ST', name: 'Sóc Trăng', countryCode: 'VN' },
        { id: 'VN-SL', name: 'Sơn La', countryCode: 'VN' },
        { id: 'VN-TN', name: 'Tây Ninh', countryCode: 'VN' },
        { id: 'VN-TB', name: 'Thái Bình', countryCode: 'VN' },
        { id: 'VN-TY', name: 'Thái Nguyên', countryCode: 'VN' },
        { id: 'VN-TH', name: 'Thanh Hóa', countryCode: 'VN' },
        { id: 'VN-TT', name: 'Thừa Thiên Huế', countryCode: 'VN' },
        { id: 'VN-TG', name: 'Tiền Giang', countryCode: 'VN' },
        { id: 'VN-TV', name: 'Trà Vinh', countryCode: 'VN' },
        { id: 'VN-TQ', name: 'Tuyên Quang', countryCode: 'VN' },
        { id: 'VN-VL', name: 'Vĩnh Long', countryCode: 'VN' },
        { id: 'VN-VC', name: 'Vĩnh Phúc', countryCode: 'VN' },
        { id: 'VN-YB', name: 'Yên Bái', countryCode: 'VN' }
    ],
    // Hoa Kỳ
    'US': [
        { id: 'US-AL', name: 'Alabama', countryCode: 'US' },
        { id: 'US-AK', name: 'Alaska', countryCode: 'US' },
        { id: 'US-AZ', name: 'Arizona', countryCode: 'US' },
        { id: 'US-AR', name: 'Arkansas', countryCode: 'US' },
        { id: 'US-CA', name: 'California', countryCode: 'US' },
        { id: 'US-CO', name: 'Colorado', countryCode: 'US' },
        { id: 'US-CT', name: 'Connecticut', countryCode: 'US' },
        { id: 'US-DE', name: 'Delaware', countryCode: 'US' },
        { id: 'US-FL', name: 'Florida', countryCode: 'US' },
        { id: 'US-GA', name: 'Georgia', countryCode: 'US' },
        { id: 'US-HI', name: 'Hawaii', countryCode: 'US' },
        { id: 'US-ID', name: 'Idaho', countryCode: 'US' },
        { id: 'US-IL', name: 'Illinois', countryCode: 'US' },
        { id: 'US-IN', name: 'Indiana', countryCode: 'US' },
        { id: 'US-IA', name: 'Iowa', countryCode: 'US' },
        { id: 'US-KS', name: 'Kansas', countryCode: 'US' },
        { id: 'US-KY', name: 'Kentucky', countryCode: 'US' },
        { id: 'US-LA', name: 'Louisiana', countryCode: 'US' },
        { id: 'US-ME', name: 'Maine', countryCode: 'US' },
        { id: 'US-MD', name: 'Maryland', countryCode: 'US' },
        { id: 'US-MA', name: 'Massachusetts', countryCode: 'US' },
        { id: 'US-MI', name: 'Michigan', countryCode: 'US' },
        { id: 'US-MN', name: 'Minnesota', countryCode: 'US' },
        { id: 'US-MS', name: 'Mississippi', countryCode: 'US' },
        { id: 'US-MO', name: 'Missouri', countryCode: 'US' },
        { id: 'US-MT', name: 'Montana', countryCode: 'US' },
        { id: 'US-NE', name: 'Nebraska', countryCode: 'US' },
        { id: 'US-NV', name: 'Nevada', countryCode: 'US' },
        { id: 'US-NH', name: 'New Hampshire', countryCode: 'US' },
        { id: 'US-NJ', name: 'New Jersey', countryCode: 'US' },
        { id: 'US-NM', name: 'New Mexico', countryCode: 'US' },
        { id: 'US-NY', name: 'New York', countryCode: 'US' },
        { id: 'US-NC', name: 'North Carolina', countryCode: 'US' },
        { id: 'US-ND', name: 'North Dakota', countryCode: 'US' },
        { id: 'US-OH', name: 'Ohio', countryCode: 'US' },
        { id: 'US-OK', name: 'Oklahoma', countryCode: 'US' },
        { id: 'US-OR', name: 'Oregon', countryCode: 'US' },
        { id: 'US-PA', name: 'Pennsylvania', countryCode: 'US' },
        { id: 'US-RI', name: 'Rhode Island', countryCode: 'US' },
        { id: 'US-SC', name: 'South Carolina', countryCode: 'US' },
        { id: 'US-SD', name: 'South Dakota', countryCode: 'US' },
        { id: 'US-TN', name: 'Tennessee', countryCode: 'US' },
        { id: 'US-TX', name: 'Texas', countryCode: 'US' },
        { id: 'US-UT', name: 'Utah', countryCode: 'US' },
        { id: 'US-VT', name: 'Vermont', countryCode: 'US' },
        { id: 'US-VA', name: 'Virginia', countryCode: 'US' },
        { id: 'US-WA', name: 'Washington', countryCode: 'US' },
        { id: 'US-WV', name: 'West Virginia', countryCode: 'US' },
        { id: 'US-WI', name: 'Wisconsin', countryCode: 'US' },
        { id: 'US-WY', name: 'Wyoming', countryCode: 'US' },
        { id: 'US-DC', name: 'District of Columbia', countryCode: 'US' }
    ],
    // Thêm một số quốc gia phổ biến khác
    'GB': [
        { id: 'GB-ENG', name: 'England', countryCode: 'GB' },
        { id: 'GB-SCT', name: 'Scotland', countryCode: 'GB' },
        { id: 'GB-WLS', name: 'Wales', countryCode: 'GB' },
        { id: 'GB-NIR', name: 'Northern Ireland', countryCode: 'GB' },
        { id: 'GB-LND', name: 'London', countryCode: 'GB' },
        { id: 'GB-MAN', name: 'Manchester', countryCode: 'GB' },
        { id: 'GB-BIR', name: 'Birmingham', countryCode: 'GB' },
        { id: 'GB-LIV', name: 'Liverpool', countryCode: 'GB' },
        { id: 'GB-EDI', name: 'Edinburgh', countryCode: 'GB' },
        { id: 'GB-GLA', name: 'Glasgow', countryCode: 'GB' }
    ],
    'CA': [
        { id: 'CA-AB', name: 'Alberta', countryCode: 'CA' },
        { id: 'CA-BC', name: 'British Columbia', countryCode: 'CA' },
        { id: 'CA-MB', name: 'Manitoba', countryCode: 'CA' },
        { id: 'CA-NB', name: 'New Brunswick', countryCode: 'CA' },
        { id: 'CA-NL', name: 'Newfoundland and Labrador', countryCode: 'CA' },
        { id: 'CA-NS', name: 'Nova Scotia', countryCode: 'CA' },
        { id: 'CA-ON', name: 'Ontario', countryCode: 'CA' },
        { id: 'CA-PE', name: 'Prince Edward Island', countryCode: 'CA' },
        { id: 'CA-QC', name: 'Quebec', countryCode: 'CA' },
        { id: 'CA-SK', name: 'Saskatchewan', countryCode: 'CA' },
        { id: 'CA-NT', name: 'Northwest Territories', countryCode: 'CA' },
        { id: 'CA-NU', name: 'Nunavut', countryCode: 'CA' },
        { id: 'CA-YT', name: 'Yukon', countryCode: 'CA' }
    ],
    'AU': [
        { id: 'AU-ACT', name: 'Australian Capital Territory', countryCode: 'AU' },
        { id: 'AU-NSW', name: 'New South Wales', countryCode: 'AU' },
        { id: 'AU-NT', name: 'Northern Territory', countryCode: 'AU' },
        { id: 'AU-QLD', name: 'Queensland', countryCode: 'AU' },
        { id: 'AU-SA', name: 'South Australia', countryCode: 'AU' },
        { id: 'AU-TAS', name: 'Tasmania', countryCode: 'AU' },
        { id: 'AU-VIC', name: 'Victoria', countryCode: 'AU' },
        { id: 'AU-WA', name: 'Western Australia', countryCode: 'AU' }
    ],
    'FR': [
        { id: 'FR-ARA', name: 'Auvergne-Rhône-Alpes', countryCode: 'FR' },
        { id: 'FR-BFC', name: 'Bourgogne-Franche-Comté', countryCode: 'FR' },
        { id: 'FR-BRE', name: 'Bretagne', countryCode: 'FR' },
        { id: 'FR-CVL', name: 'Centre-Val de Loire', countryCode: 'FR' },
        { id: 'FR-COR', name: 'Corse', countryCode: 'FR' },
        { id: 'FR-GES', name: 'Grand Est', countryCode: 'FR' },
        { id: 'FR-HDF', name: 'Hauts-de-France', countryCode: 'FR' },
        { id: 'FR-IDF', name: 'Île-de-France', countryCode: 'FR' },
        { id: 'FR-NOR', name: 'Normandie', countryCode: 'FR' },
        { id: 'FR-NAQ', name: 'Nouvelle-Aquitaine', countryCode: 'FR' },
        { id: 'FR-OCC', name: 'Occitanie', countryCode: 'FR' },
        { id: 'FR-PDL', name: 'Pays de la Loire', countryCode: 'FR' },
        { id: 'FR-PAC', name: "Provence-Alpes-Côte d'Azur", countryCode: 'FR' }
    ],
    'DE': [
        { id: 'DE-BW', name: 'Baden-Württemberg', countryCode: 'DE' },
        { id: 'DE-BY', name: 'Bayern', countryCode: 'DE' },
        { id: 'DE-BE', name: 'Berlin', countryCode: 'DE' },
        { id: 'DE-BB', name: 'Brandenburg', countryCode: 'DE' },
        { id: 'DE-HB', name: 'Bremen', countryCode: 'DE' },
        { id: 'DE-HH', name: 'Hamburg', countryCode: 'DE' },
        { id: 'DE-HE', name: 'Hessen', countryCode: 'DE' },
        { id: 'DE-MV', name: 'Mecklenburg-Vorpommern', countryCode: 'DE' },
        { id: 'DE-NI', name: 'Niedersachsen', countryCode: 'DE' },
        { id: 'DE-NW', name: 'Nordrhein-Westfalen', countryCode: 'DE' },
        { id: 'DE-RP', name: 'Rheinland-Pfalz', countryCode: 'DE' },
        { id: 'DE-SL', name: 'Saarland', countryCode: 'DE' },
        { id: 'DE-SN', name: 'Sachsen', countryCode: 'DE' },
        { id: 'DE-ST', name: 'Sachsen-Anhalt', countryCode: 'DE' },
        { id: 'DE-SH', name: 'Schleswig-Holstein', countryCode: 'DE' },
        { id: 'DE-TH', name: 'Thüringen', countryCode: 'DE' }
    ],
    // Thêm các quốc gia khác khi cần thiết
};

// Hàm trợ giúp để lấy danh sách tỉnh thành theo mã quốc gia
export const getProvincesByCountryCode = (countryCode: string): ProvinceData[] => {
    return provincesData[countryCode] || [];
};